version: '3.8'

services:
  db:
    image: mysql
    container_name: companydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: companydb
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - 3307:3307
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    